### ISSUE TITLE
Many blocks and items are not compostable.

### ISSUE THREAD

**Issue by Darkhax** [mrsterner/witchery#10]
Hello, we noticed a few items that would normally be compostable like belladonna seeds can not be composted. Is this something you would consider adding/fixing?

Witchery 0.1.2f
NeoForge 21.1.74

**Comment by mrsterner** [comment]
Yes totally, it might even be added in dev already since we have about trice as much content unreleased here on github, new alpha will drop soon

**Comment by mrsterner** [comment]
added in #c8e1592
